{
  "name": "iamcoreyg",
  "version": "1.0.0",
  "description": "Personal blog and projects site for Corey G",
  "main": "app.js",
  "scripts": {
    "start": "node app.js",
    "dev": "nodemon app.js"
  },
  "engines": {
    "node": "20.x",
    "yarn": "4.x"
  },
  "dependencies": {
    "express": "^4.19.2"
  },
  "devDependencies": {
    "nodemon": "^3.0.1"
  }
}
